module.exports = {
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',
    REQUEST_PRODUCTS: 'REQUEST_PRODUCTS',
    GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
    REQUEST_PRODUCT_DETAIL: 'REQUEST_PRODUCT_DETAIL',
    RESET_PRODUCTS: 'RESET_PRODUCTS',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    RESET_LOGIN_PROCESS: 'RESET_LOGIN_PROCESS'
};